parameters:
  bml.twig_swiftmailer.class: Bml\TwigSwiftMailerBundle\Mailer\TwigSwiftMailer

services:
  bml.twig_swiftmailer:
    class: %bml.twig_swiftmailer.class%
    arguments: [@twig, @swiftmailer.mailer]
